#! /usr/bin/env python

import sys

from statistics import mean, pstdev, median_low, median_high


def readfile(name, period):
	file = open(name, 'r')
	lines = []
	if file is None:
		return None
	for line in file:
		if line is not "":
			lines.append(float(line.replace('\n', '')))
	return lines[-int(period):]

def get_moy(lines):
	moy = 0
	for line in lines:
		moy += line
	return mean(lines)

def main():
	try:
		file = sys.argv[2]
		period = sys.argv[3]
		deviation = float(sys.argv[4])
	except:
		print("Error arguments")
		return 1

	lines = readfile(file, period)
	B_high = get_moy(lines) + (pstdev(lines) * deviation)
	B_low = get_moy(lines) - (pstdev(lines) * deviation)
	print("MA: {0:0.2f}".format(get_moy(lines)))
	print("SD: {0:0.2f}".format(pstdev(lines)))
	print("B+: {0:0.2f}".format(B_high))
	print("B-: {0:0.2f}".format(B_low))

if __name__ == '__main__':
	main()