#! /usr/bin/env python3

import sys
import os.path

from calc import moy, standard, variance, readfile


def display_help():
	print("Bollinger Bands\n")
	print("USAGE")
	print("\t./bollinger [-h] period standard_dev indexes_file index_number\n")

	print("\tperiod\t\tnumber of indexes for the moving average")
	print("\tstandard_dev\tstandard deviation coefficient to apply")
	print("\tindexes_file\tfile containing daily indexes")
	print("\tindex_number\tindex number to compute moving average and Bollinger bands\n")

	print("OPTIONS")
	print("\t-h\t\tprint the usage and quit")

def print_args(index, period, coef):
	print("INPUT")
	print("Index: {}".format(index))
	print("Period: {}".format(period))
	print("SD_coef: {0:0.2f}".format(coef))

def print_output(lines, index, period, standard_dev):
	if lines is None:
		sys.exit(84)
	B_high = moy(lines) + (standard_dev * standard(lines))
	B_low = moy(lines) - (standard_dev * standard(lines))

	print()
	print("OUTPUT")
	try:
		print("MA: {0:0.2f}".format(moy(lines)))
	except:
		print("No values for this index")
		sys.exit(84)
	print("SD: {0:0.2f}".format(standard(lines)))
	print("B+: {0:0.2f}".format(B_high))
	print("B-: {0:0.2f}".format(B_low))
	

def main():
	try:
		period = sys.argv[1]
		standard_dev = float(sys.argv[2])
		file = sys.argv[3]
		index_number = int(sys.argv[4])
	except:
		display_help()
		sys.exit(84)
	if period == "-h":
		display_help()
		sys.exit(0)
	elif not os.path.isfile(file):
		sys.exit(84)
	
	period = int(period)
	if readfile(file, index_number, int(period)) is None:
		sys.exit(84)
	print_args(index_number, period, standard_dev)
	print_output(readfile(file, index_number, period), index_number, int(period), standard_dev)
	

if __name__ == '__main__':
	main()