#! /usr/bin/env python

import sys

def readfile(name, period):
	file = open(name, 'r')
	lines = []
	if file is None:
		return None
	for line in file:
		if line is not "":
			lines.append(float(line.replace('\n', '')))
	return lines[-int(period):]

def moy(lines):
	moy = 0
	for nb in lines:
		moy += nb
	moy /= len(lines)
	return moy

def standard_dev(lines):
    return variance(lines)**0.5

def variance(lines):
    moyen = moy(lines)
    return moy([(x-moyen)**2 for x in lines])


def main():
	try:
		file = sys.argv[2]
		period = sys.argv[3]
		deviation = float(sys.argv[4])
	except:
		print("Error arguments")
		return 1

	lines = readfile(file, period)
	B_high = moy(lines) + (standard_dev(lines) * deviation)
	B_low = moy(lines) - (standard_dev(lines) * deviation)
	print("MA: {0:0.2f}".format(moy(lines)))
	print("SD: {0:0.2f}".format(standard_dev(lines)))
	print("B+: {0:0.2f}".format(B_high))
	print("B-: {0:0.2f}".format(B_low))

if __name__ == '__main__':
	main()