#! /usr/bin/env python

import sys
import argparse
import os
from urllib.request import Request, urlopen

import json

from calc import moy, standard, variance, readfile, deviation

from graph import print_graph

def display_help():
	print("Bollinger Bands\n")
	print("USAGE")
	print("\t./bollinger [-h] period standard_dev indexes_file index_number\n")

	print("\tperiod\t\tnumber of indexes for the moving average")
	print("\tstandard_dev\tstandard deviation coefficient to apply")
	print("\tindexes_file\tfile containing daily indexes")
	print("\tindex_number\tindex number to compute moving average and Bollinger bands\n")

	print("OPTIONS")
	print("\t-h\t\tprint the usage and quit")
	print("\t-g\t\tprint a graphical of bollinger bands")

def print_args(index, period, coef):
	print("INPUT")
	print("Index: {}".format(index))
	print("Period: {}".format(period))
	print("SD_coef: {0:0.2f}".format(coef))

def print_output(lines, index, period, standard_dev):
	B_high, B_low = deviation(lines, standard_dev)
	print()
	print("OUTPUT")
	try:
		print("MA: {0:0.2f}".format(moy(lines)))
	except:
		print("No values for this index")
		sys.exit(84)
	print("SD: {0:0.2f}".format(standard(lines)))
	print("B+: {0:0.2f}".format(B_high))
	print("B-: {0:0.2f}".format(B_low))
	

def main():
	parser = argparse.ArgumentParser()
	parser.add_argument("period", help="number of indexes for the moving average", type=int)
	parser.add_argument("standard_dev", help="standard deviation coefficient to apply", type=float)
	parser.add_argument("-f", "--file", help="file containing daily indexes", type=str)
	parser.add_argument("index_number", help="index number to compute moving average and Bollinger bands", type=int)
	parser.add_argument("-g", "--graph", help="print a graph of bollinger bands", action="store_true")
	parser.add_argument("-u", "--url", help="load data from API", type=str)
	parser.add_argument("-d", "--data", help="object to load from API route", type=str)
	args = parser.parse_args()

	if args.graph:
		if args.url is not None and args.data is not None:
			print(args.url)
			req = Request(args.url, headers={'User-Agent': 'Mozilla/5.0'})
			print(urlopen(req).read())
			try:
				data = json.loads(urlopen(req).read())[args.data]
			except:
				print("Data field is unavailable")
				exit(84)
			t = [data[x] for x in data]
			print_graph(t, args.standard_dev)
			exit(0)
		if args.file is not None:
			print_graph(readfile(args.file, args.index_number, args.period), args.standard_dev)
	elif args.file and not os.path.isfile(args.file):
		print("Can't find file '{}'".format(args.indexes_file), file=sys.stderr)
		sys.exit(84)
	else:
		if readfile(args.file, args.index_number, args.period) is None:
			sys.exit(84)
		print_args(args.index_number, args.period, args.standard_dev)
		print_output(readfile(args.file, args.index_number, args.period), args.index_number, args.period, args.standard_dev)
	

if __name__ == '__main__':
	main()